services:
  web-app:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: sqlite-db:/db-data/db.sqlite
    depends_on:
      - sqlite-db
    ports:
      - 3000:3000
  meilisearch:
      container_name: search-meilisearch
      image: getmeili/meilisearch:v1.7.3
      restart: always
      ports:
        - "7700:7700"
      # user: "${UID}:${GID}"
      environment:
        - MEILI_NO_ANALYTICS=true
        - MEILI_MASTER_KEY=${TOKEN}
  sqlite-db:
    image: nouchka/sqlite3:latest
    volumes:
      - db-data:/data
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt


