services:
  traefik:
      image: traefik:v3.2
      command:
        - "--providers.docker"
        - "--providers.docker.exposedbydefault=false"
        - "--entryPoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=info@simanga.dev"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      ports:
        - mode: host
          protocol: tcp
          published: 80
          target: 80
        - mode: host
          protocol: tcp
          published: 443
          target: 443
      volumes:
        - data:/letsencrypt
        - /var/run/docker.sock:/var/run/docker.sock
  web-app:
    image: ghcr.io/simanga-dev/matric-dashboard:latest
    labels:
       - "traefik.enable=true"
       - "traefik.http.services.matric.loadbalancer.server.port=3000"
       - "traefik.http.routers.matric.rule=Host(`matric.simanga.dev`)"
       - "traefik.http.routers.matric.entrypoints=websecure"
       - "traefik.http.routers.matric.tls.certresolver=myresolver"
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/data/db.sqlite
      - MEILI_URL=http://meilisearch:7700
    depends_on:
      - meilisearch
    secrets:
      - master-key-two
    # ports:
    #   - 3000:3000
    volumes:
      - data:/data  # Mount to a directory
    deploy:
          update_config:
            order: start-first
    command: /bin/sh -c "export MEILI_TOKEN=$$(cat /run/secrets/master-key-two) && exec bun start"
  meilisearch:
     image: getmeili/meilisearch:v1.7.3
     restart: always
     # ports:
     #   - "7700:7700"
     user: "${UID}:${GID}"
     secrets:
       - master-key-two
     environment:
        - MEILI_NO_ANALYTICS=true
     volumes:
      - data:/meili_data  # Separate volume for MeiliSearch
     command: /bin/sh -c "export MEILI_MASTER_KEY=$$(cat /run/secrets/master-key-two) && exec meilisearch"
volumes:
  data:
secrets:
  master-key-two:
    external: true
