services:
  web-app:
    container_name: nextjs-web-application
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      MEILI_URL: ${MEILI_URL}
      MEILI_TOKEN: ${MEILI_TOKEN}
    depends_on:
      - meilisearch
    ports:
      - 3000:3000
  meilisearch:
      container_name: search-meilisearch
      image: getmeili/meilisearch:v1.7.3
      restart: always
      ports:
        - "7700:7700"
      # user: "${UID}:${GID}"
      environment:
        - MEILI_NO_ANALYTICS=true
        - MEILI_MASTER_KEY=${MEILI_TOKEN}
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt


