@Host.Api_HostAddress = https://search.simanga.dev
@TOKEN = {{$dotenv MEILI_MASTER_KEY }}

##### first queries
GET {{Host.Api_HostAddress}}/tasks
Authorization: Bearer {{TOKEN}}


##### first queries
GET {{Host.Api_HostAddress}}




#####
GET https://api.agify.io?name=Hendry




### New amazing request
GET https://jsonplaceholder.typicode.com/posts




#### This query make sure I win
POST {{Host.Api_HostAddress}}/indexes/schools/search
Content-Type: application/json
Authorization: Bearer {{MEILI_TOKEN}}

{
  "q": "s"
}



##### first queries
GET http://0.0.0.0:7700/tasks
Authorization: Bearer {{MEILI_TOKEN}}


##### first queries
GET http://0.0.0.0:7700/keys
Authorization: Bearer {{MEILI_TOKEN}}


#######
POST http://localhost:7700/indexes/schools/search
Authorization: Bearer {{MEILI_TOKEN}}
Content-Type: application/json

{
"q": "sincobi"
}
